(function(){'use strict';
const base='https://github.com/agentrust-io/integrations/tree/main/';
const items=[
{name:'Claude Code',vendor:'agentrust-io',path:'claude-code',stack:['Agent Manifest','TRACE'],type:'Developer tools',mark:'CC',featured:1,description:'Emits a signed Agent Manifest and TRACE record per session, with composition-drift detection.'},
{name:'agentrust-codex',vendor:'agentrust-io',path:'plugins/agentrust-codex',stack:['Agent Manifest','TRACE'],type:'Developer tools',mark:'CX',featured:2,description:'Fingerprints Codex agent configuration, detects workspace drift, and emits signed trust evidence.'},
{name:'LangChain',vendor:'agentrust-io',path:'integrations/langchain',stack:['TRACE'],type:'Frameworks',mark:'LC',featured:3,description:'Emits a TRACE Trust Record from a LangChain run through a payload-safe callback handler.'},
{name:'LlamaIndex',vendor:'agentrust-io',path:'integrations/llamaindex',stack:['TRACE'],type:'Frameworks',mark:'LI',featured:4,description:'Turns LlamaIndex instrumentation events into TRACE records using an explicit payload allow-list.'},
{name:'OpenTelemetry GenAI',vendor:'agentrust-io',path:'integrations/otel-genai',stack:['TRACE'],type:'Observability',mark:'OT',featured:5,description:'Builds a TRACE Trust Record from OpenTelemetry GenAI spans as an unsigned telemetry import.'},
{name:'Agent Sentinel',vendor:'a1k7',path:'integrations/sentinel',stack:['TRACE'],type:'Security & policy',mark:'AS',featured:6,description:'Detects delegation escalation, tool drift, identity drift, and policy avoidance across agent fleets.'},
{name:'Agent Passport System',vendor:'aeoess',path:'integrations/aeoess-aps',stack:['TRACE'],type:'Identity & trust',mark:'AP',description:'Maps a verified, Ed25519-signed Agent Passport policy decision onto a TRACE Trust Record.'},
{name:'Agentic SpendGuard',vendor:'SpendGuard',path:'integrations/spendguard',stack:['TRACE'],type:'Security & policy',mark:'$G',description:'Gates agent tool calls against reserved budget and creates a signed, hash-chained decision record.'},
{name:'comply54',vendor:'comply54',path:'integrations/comply54',stack:['TRACE'],type:'Compliance',mark:'C5',description:'Maps African regulatory policy decisions from comply54 into signed TRACE evidence.'},
{name:'DecisionAssure',vendor:'DecisionAssure',path:'integrations/decisionassure',stack:['TRACE'],type:'Security & policy',mark:'DA',description:'Converts a runtime governance trace into a third-party-asserted TRACE Trust Record.'},
{name:'Nobulex',vendor:'Nobulex',path:'integrations/nobulex',stack:['TRACE'],type:'Evidence & receipts',mark:'NX',description:'Produces signed, canonical action receipts usable as external execution evidence in TRACE.'},
{name:'ramen-ai cMCP Adapter',vendor:'ramen-ai',path:'integrations/ramen-ai-cmcp',stack:['cMCP','TRACE'],type:'Evidence & receipts',mark:'RA',description:'Verifies cMCP receipts and exports a natively signed, software-only TRACE Trust Record.'},
{name:'SAGE AgenTrust Bridge',vendor:'SAGE',path:'integrations/sage-agenttrust',stack:['cMCP','TRACE'],type:'Security & policy',mark:'SG',description:'Verifies TRACE or cMCP runtime evidence before admitting memory to a SAGE consensus node.'},
{name:'Shadow AI Discovery',vendor:'agentrust-io',path:'integrations/shadow-ai',stack:['cMCP','Agent Manifest'],type:'Identity & trust',mark:'SH',description:'Finds undeclared agents making MCP tool calls and creates discovery events for remediation.'},
{name:'Scheduled Agents',vendor:'agentrust-io',path:'scheduled-agents',stack:['TRACE'],type:'Developer tools',mark:'SA',description:'Detects drift in unattended agent routines and emits a signed TRACE record for each run.'}
];
const stacks=['TRACE','cMCP','Agent Manifest'],types=[...new Set(items.map(x=>x.type))].sort(),state={query:'',stacks:new Set(),types:new Set(),sort:'featured'},search=document.getElementById('market-search'),grid=document.getElementById('market-grid'),empty=document.getElementById('market-empty');
const slug=v=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function esc(v){const n=document.createElement('span');n.textContent=v;return n.innerHTML}
function card(x,compact){const tags=x.stack.map(t=>`<span>${esc(t)}</span>`).join('');return `<article class="market-card${compact?' market-card-featured':''}"><div class="market-card-top"><span class="market-mark mark-${slug(x.type)}">${esc(x.mark)}</span><span class="market-tier"><i></i> Community</span></div><div><p class="market-vendor">By ${esc(x.vendor)}</p><h3>${esc(x.name)}</h3><p class="market-description">${esc(x.description)}</p></div><div class="market-card-foot"><div class="market-tags">${tags}</div><a href="${base+x.path}" aria-label="View ${esc(x.name)} integration">View integration <span>↗</span></a></div></article>`}
function addFilters(id,values,key){document.getElementById(id).innerHTML=values.map(v=>{const count=items.filter(x=>key==='stacks'?x.stack.includes(v):x.type===v).length,input=`${key}-${slug(v)}`;return `<label for="${input}"><input type="checkbox" id="${input}" value="${esc(v)}" data-filter="${key}"><span>${esc(v)}</span><b>${count}</b></label>`}).join('')}
function render(){const words=state.query.toLowerCase().trim().split(/\s+/).filter(Boolean);let shown=items.filter(x=>{const hay=[x.name,x.vendor,x.type,x.description,...x.stack].join(' ').toLowerCase();return words.every(w=>hay.includes(w))&&(!state.stacks.size||[...state.stacks].every(s=>x.stack.includes(s)))&&(!state.types.size||state.types.has(x.type))});if(state.sort==='az')shown.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort==='za')shown.sort((a,b)=>b.name.localeCompare(a.name));else shown.sort((a,b)=>(a.featured||99)-(b.featured||99)||a.name.localeCompare(b.name));grid.innerHTML=shown.map(x=>card(x)).join('');grid.hidden=!shown.length;empty.hidden=!!shown.length;document.getElementById('result-count').textContent=shown.length;document.getElementById('result-label').textContent=shown.length===1?'integration':'integrations';const chips=[];if(state.query)chips.push(`<button data-clear="query">Search: “${esc(state.query)}” ×</button>`);state.stacks.forEach(v=>chips.push(`<button data-clear="stacks" data-value="${esc(v)}">${esc(v)} ×</button>`));state.types.forEach(v=>chips.push(`<button data-clear="types" data-value="${esc(v)}">${esc(v)} ×</button>`));document.getElementById('active-filters').innerHTML=chips.join('');const p=new URLSearchParams;if(state.query)p.set('q',state.query);if(state.stacks.size)p.set('stack',[...state.stacks].join(','));if(state.types.size)p.set('type',[...state.types].join(','));if(state.sort!=='featured')p.set('sort',state.sort);history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}${location.hash}`)}
function clear(){state.query='';state.stacks.clear();state.types.clear();state.sort='featured';search.value='';document.getElementById('market-sort').value='featured';document.querySelectorAll('[data-filter]').forEach(i=>i.checked=false);render()}
addFilters('stack-filters',stacks,'stacks');addFilters('type-filters',types,'types');document.getElementById('featured-list').innerHTML=items.filter(x=>x.featured&&x.featured<=3).map(x=>card(x,true)).join('');document.getElementById('hero-count').textContent=items.length;
const params=new URLSearchParams(location.search);state.query=params.get('q')||'';state.sort=['az','za'].includes(params.get('sort'))?params.get('sort'):'featured';(params.get('stack')||'').split(',').filter(v=>stacks.includes(v)).forEach(v=>state.stacks.add(v));(params.get('type')||'').split(',').filter(v=>types.includes(v)).forEach(v=>state.types.add(v));search.value=state.query;document.getElementById('market-sort').value=state.sort;document.querySelectorAll('[data-filter]').forEach(i=>i.checked=state[i.dataset.filter].has(i.value));
search.addEventListener('input',()=>{state.query=search.value;render()});document.getElementById('market-sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.querySelectorAll('[data-filter]').forEach(i=>i.addEventListener('change',()=>{const set=state[i.dataset.filter];i.checked?set.add(i.value):set.delete(i.value);render()}));document.getElementById('active-filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.clear==='query'){state.query='';search.value=''}else{state[b.dataset.clear].delete(b.dataset.value);const i=[...document.querySelectorAll('[data-filter]')].find(x=>x.value===b.dataset.value);if(i)i.checked=false}render()});document.getElementById('clear-filters').addEventListener('click',clear);document.getElementById('empty-clear').addEventListener('click',clear);document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|select|textarea/i.test(document.activeElement.tagName)){e.preventDefault();search.focus()}});render();
}());
