"""Stamp the shared site header into every agentrust-io.com page.

    python tools/build-header.py          # rewrite the header block in each page
    python tools/build-header.py --check  # fail if any page's header differs

The header itself is defined once, in tools/site_header.py. Each page carries it
between the site-header:start and site-header:end markers, and this script owns
everything between them, plus the design-system.css and supernav.js cache-bust. A hand edit
inside the markers fails CI; change site_header.py and re-run this instead.

/go/ and /marketplace/catalog/ are generated by build-controls.py and
build-discovery.py from the same render(), so they are checked here too.
"""
import argparse
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import site_header  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

# page file -> (path the header marks current, menu the page belongs to)
PAGES = {
    'index.html': (None, None),
    'community/index.html': ('/community/', None),
    'verify/index.html': ('/verify/', None),
    'quickstart/index.html': ('/quickstart/', None),
    'demos/index.html': ('/demos/', None),
    'telemetry/index.html': ('/telemetry/', None),
    'marketplace/index.html': ('/marketplace/', None),
    'marketplace/catalog/index.html': (None, 'Build'),
    'registry/index.html': ('/registry/', None),
    'go/index.html': (None, 'Specs'),
    'extensions/ca2a/v0.1/index.html': (None, 'Specs'),
    'search/index.html': ('/search/', None),
    '404.html': (None, None),
}

# check-discovery.py requires the static catalog to carry no script at all.
NO_SCRIPT = {'marketplace/catalog/index.html'}

BLOCK = re.compile(re.escape(site_header.START) + r'.*?' + re.escape(site_header.END), re.S)
CSS = re.compile(r'/design-system\.css\?v=\d+')
SUPERNAV = re.compile(r'/supernav\.js(?:\?v=\d+)?(?=")')


def stamped(text, name, page, section):
    if len(BLOCK.findall(text)) != 1:
        raise SystemExit(f'{name}: expected exactly one site-header block between the markers')
    if 'id="main"' not in text:
        raise SystemExit(f'{name}: the skip link needs an element with id="main"')
    if len(CSS.findall(text)) != 1:
        raise SystemExit(f'{name}: expected exactly one design-system.css link')
    if len(SUPERNAV.findall(text)) != (0 if name in NO_SCRIPT else 1):
        raise SystemExit(f'{name}: expected exactly one supernav.js script' if name not in NO_SCRIPT
                         else f'{name}: must not load supernav.js')
    text = BLOCK.sub(lambda _: site_header.render(page, section, script=name not in NO_SCRIPT), text)
    text = SUPERNAV.sub(f'/supernav.js?v={site_header.CSS_VERSION}', text)
    return CSS.sub(f'/design-system.css?v={site_header.CSS_VERSION}', text)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='fail if any page header differs')
    args = parser.parse_args()

    stale = []
    for name, (page, section) in PAGES.items():
        path = ROOT / name
        text = path.read_text(encoding='utf-8')
        expected = stamped(text, name, page, section)
        if expected != text:
            stale.append(name)
            if not args.check:
                path.write_text(expected, encoding='utf-8', newline='\n')
    if args.check:
        if stale:
            raise SystemExit(f'{len(stale)} page header(s) differ from tools/site_header.py: {", ".join(stale)}. '
                             'Run python tools/build-header.py and commit the result.')
        print(f'PASS site header matches tools/site_header.py on {len(PAGES)} pages')
        return
    print(f'Stamped {len(stale)} of {len(PAGES)} pages')


if __name__ == '__main__':
    sys.exit(main())
