"""Generate /go/, the agentic control set, from data/agentic-controls.json.

The control set is cited by external standards through stable permalinks, so the
pages must never drift from the data. Edit data/agentic-controls.json, then run:

    python tools/build-controls.py          # write go/index.html and go/<slug>/index.html
    python tools/build-controls.py --check  # fail if any page differs from the data

CI runs --check. A permalink that is cited elsewhere must keep resolving, so a
control that disappears from the data is an error here, not a silent deletion.
"""
import argparse
from html import escape
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import site_header  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data' / 'agentic-controls.json'
GO = ROOT / 'go'
BASE = 'https://agentrust-io.com'

# Shared chrome. These are the only strings to change when the site's look moves.
CSS_VERSION = site_header.CSS_VERSION
OG_IMAGE_ALT = 'AgenTrust: open specifications for verifiable AI'
TAGLINE = 'Open specifications for verifiable AI'
EYEBROW = '<a href="/#chain">Across the chain</a> &middot; Mapped to OpenCRE &middot; Stable permalinks'
REPO = 'https://github.com/agentrust-io/agentrust-io.github.io/blob/main'
GENERATED_COMMENT = ('<!-- Generated by tools/build-controls.py from data/agentic-controls.json. '
                     'Edit the data and re-run it; CI fails on hand edits. -->')
GENERATED_NOTE = (f'This page is generated from <a href="{REPO}/data/agentic-controls.json">agentic-controls.json</a>\n'
                  f'  by <a href="{REPO}/tools/build-controls.py">build-controls.py</a>. Edit the data, not this file.')

ENFORCEMENT_POINTS = {'agent_startup', 'agent_shutdown', 'input', 'output', 'pre_tool_call',
                      'post_tool_call', 'post_model_call'}
SLUG = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
CRE = re.compile(r'^\d{3}-\d{3}$')

_ONES = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
         'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen',
         'eighteen', 'nineteen']
_TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']


def words(n):
    if not 0 <= n < 100:
        raise ValueError(f'no word form for {n}')
    if n < 20:
        return _ONES[n]
    tens, ones = divmod(n, 10)
    return _TENS[tens] + (f'-{_ONES[ones]}' if ones else '')


def e(text):
    return escape(text, quote=True)


def load():
    data = json.loads(DATA.read_text(encoding='utf-8'))
    controls = data['controls']
    problems = []
    seen_ids, seen_slugs, families = set(), set(), []
    for c in controls:
        where = c.get('id', '<no id>')
        missing = [key for key in ('id', 'family', 'family_name', 'slug', 'name', 'enforcement_points',
                                   'requirement', 'permalink', 'opencre') if key not in c]
        if missing:
            problems.append(f'{where}: missing {", ".join(missing)}')
            continue
        if c['id'] in seen_ids:
            problems.append(f'{where}: duplicate id')
        if c['slug'] in seen_slugs or not SLUG.match(c['slug']):
            problems.append(f'{where}: slug {c["slug"]!r} is duplicated or not lowercase-hyphenated')
        seen_ids.add(c['id'])
        seen_slugs.add(c['slug'])
        if c['permalink'] != f'{BASE}/go/{c["slug"]}/':
            problems.append(f'{where}: permalink does not match slug')
        for point in c['enforcement_points']:
            if point not in ENFORCEMENT_POINTS:
                problems.append(f'{where}: unknown enforcement point {point!r}')
        if not c['opencre']:
            problems.append(f'{where}: no OpenCRE link')
        for link in c['opencre']:
            if not CRE.match(link['id']) or link['url'] != f'https://www.opencre.org/cre/{link["id"]}':
                problems.append(f'{where}: OpenCRE link {link.get("id")!r} is malformed')
        spec = c.get('spec')
        if spec is not None:
            if not spec.get('topic'):
                problems.append(f'{where}: spec needs a topic, the lowercase phrase used in prose')
            if spec.get('status') not in ('private', 'public'):
                problems.append(f'{where}: spec.status must be private or public')
            elif spec['status'] == 'public' and not (spec.get('name') and str(spec.get('url', '')).startswith('https://')):
                problems.append(f'{where}: a public spec needs a name and an https url')
        if families and families[-1] == c['family']:
            continue
        if c['family'] in families:
            problems.append(f'{where}: family {c["family"]} is not contiguous')
        families.append(c['family'])
    if problems:
        raise SystemExit('data/agentic-controls.json is invalid:\n  ' + '\n  '.join(problems))
    return data, controls


def head(title, description, canonical, robots, og_title, og_url, extra=''):
    return f'''<!DOCTYPE html>
<html lang="en">
{GENERATED_COMMENT}
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{canonical}">
<meta name="robots" content="{robots}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="AgenTrust">
<meta property="og:title" content="{og_title}">
<meta property="og:description" content="{description}">
<meta property="og:url" content="{og_url}">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="{BASE}/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{OG_IMAGE_ALT}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{og_title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{BASE}/og.png">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
{extra}'''


FOOTER = '''<footer class="site-footer"><div class="wrap">
  <div class="foot-in">
    <div class="foot-brand">
      <a class="wordmark" href="/">AgenTrust</a>
      <div class="tagline">{tagline}</div>
    </div>
    <div class="foot-links">
      <a href="/">Home</a>
      <a href="/quickstart/">Get started</a>
      <a href="/demos/">Demos</a>
      <a href="https://github.com/agentrust-io">GitHub</a>
    </div>
  </div>
  <div class="foot-legal">&copy; 2026 AgenTrust Contributors &middot; MIT licensed &middot; agentrust-io.com</div>
</div></footer>

<script src="/supernav.js?v=''' + CSS_VERSION + '''"></script>
<script src="/page.js"></script>
</body>
</html>
'''


def card(c):
    tags = ''.join(f'<span class="tag">{e(p)}</span> ' for p in c['enforcement_points'])
    cres = ' '.join(f'<a class="tag quiet" href="{e(o["url"])}">{e(o["name"])}</a>' for o in c['opencre'])
    lines = [
        '',
        '  <div class="card" style="margin-top:1.5rem;">',
        f'    <h4 id="{c["slug"]}"><span class="meta">{e(c["id"])}</span> {e(c["name"])}</h4>',
        f'    {tags}',
        f'    <p>{e(c["requirement"])}</p>',
        f'    <p class="meta">Common Requirements: {cres}</p>',
    ]
    spec = c.get('spec') or {}
    if spec.get('status') == 'public':
        lines.append(f'    <p class="meta">Specification: <a href="{e(spec["url"])}">{e(spec["name"])}</a></p>')
    lines += [f'    <p class="meta">Permalink: <code>{c["permalink"]}</code></p>', '  </div>']
    return lines


def private_bullet(controls):
    private = [c for c in controls if (c.get('spec') or {}).get('status') == 'private']
    if not private:
        return []
    names = [c['spec']['topic'] for c in private]
    listed = names[0] if len(names) == 1 else ', '.join(names[:-1]) + ' and ' + names[-1]
    one = len(private) == 1
    return [
        f'    <li>{words(len(private)).capitalize()} of the controls, {listed}, {"is" if one else "are"} drawn from',
        f'    {"a specification" if one else "specifications"} that {"is" if one else "are"} still in private '
        f'pre-standardization. {"Its permalink resolves" if one else "Their permalinks resolve"} here and',
        f'    will point deeper once {"that specification is" if one else "those specifications are"} public.</li>',
    ]


def render_index(controls):
    total = len(controls)
    with_point = sum(1 for c in controls if c['enforcement_points'])
    links = sum(len(c['opencre']) for c in controls)
    unique = len({o['id'] for c in controls for o in c['opencre']})
    description = (f'The AgenTrust agentic control set: {total} controls for AI agents, each one requirement '
                   'cross-linked to its Common Requirement in OpenCRE. Stable permalinks at /go/.')
    ld = f'''<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "TechArticle",
  "name": "AgenTrust Agentic Controls",
  "description": "{words(total).capitalize()} agentic security controls, each cross-linked to its Common Requirement in OpenCRE.",
  "url": "{BASE}/go/",
  "license": "https://opensource.org/licenses/MIT",
  "publisher": {{ "@id": "{BASE}/#organization" }}
}}
</script>
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {{ "@type": "ListItem", "position": 1, "name": "AgenTrust", "item": "{BASE}/" }},
    {{ "@type": "ListItem", "position": 2, "name": "AgenTrust Agentic Controls", "item": "{BASE}/go/" }}
  ]
}}
</script>

<link rel="stylesheet" href="/design-system.css?v={CSS_VERSION}">
</head>
<body class="at-page">
'''
    header = site_header.render(section="Specs")
    body = [f'''
{header}

<div class="hero"><div class="wrap">
  <span class="eyebrow">{EYEBROW}</span>
  <h1>AgenTrust<br>Agentic Controls</h1>
  <p class="sub">{words(total).capitalize()} controls for AI agents, each stated as one requirement and cross-linked to the
  Common Requirement that already covers it in OpenCRE. Every control has a stable permalink so an
  external standard can cite it without the link rotting.</p>
  <div><span class="status">{total} controls &middot; {links} OpenCRE links &middot; {unique} Common Requirements</span></div>
</div></div>

<nav class="on-this-page" aria-label="On this page">
  <span>On this page</span>
  <a href="#controls">Controls</a>
  <a href="#opencre">OpenCRE</a>
  <a href="#limits">Limits</a>
</nav>

<main id="main">

<section id="opencre">
  <span class="label">How to read this</span>
  <h2>The links point outward on purpose</h2>
  <p>Most of what an agent needs is not new. Identity, least privilege, logging, injection handling and
  rate limiting are decades old, and OpenCRE already organizes them across ASVS, CWE, ISO 27001,
  NIST 800-53, SAMM and the OWASP AI Exchange. So each control below names the Common Requirement it
  belongs to rather than restating it.</p>
  <p>Where a control reads new, it is usually the same requirement applied to a different subject: a
  non-human principal, a grant derived from another grant, or a platform the relying party does not
  control. That distinction is what the OpenCRE links make visible.</p>
  <div class="callout"><p><strong>This is a mapping, not a conformance claim.</strong> A link to a
  Common Requirement says a control belongs to that topic. It is not evidence that anything is
  implemented, tested, or deployed.</p></div>
</section>

<section id="controls">
  <span class="label">The control set</span>
  <h2>{words(total).capitalize()} controls</h2>
  <p>Where a control is enforced at a specific point in the agent loop, the point is named on the
  control itself. {words(with_point).capitalize()} of the {words(total)} have one. The rest do not have a single point and are left
  unmarked rather than forced into one.</p>''']
    lines = []
    family = None
    for c in controls:
        if c['family'] != family:
            family = c['family']
            lines += ['', f'  <h3 style="margin-top:3rem;">{e(c["family"])} &middot; {e(c["family_name"])}</h3>']
        lines += card(c)
    lines += ['', '</section>', '', '<section id="limits">', '  <span class="label">Limits</span>',
              '  <h2>What this page does not do</h2>', '  <ul>',
              f'    <li>It does not claim these controls are absent from OpenCRE. Every one of the {words(total)} maps to an',
              '    existing Common Requirement. None proposes a new one.</li>',
              '    <li>It does not rank the controls or assert a maturity model over them.</li>',
              '    <li>It does not assert that any AgenTrust implementation satisfies any of them. Conformance is',
              '    tested per specification, not asserted here.</li>']
    lines += private_bullet(controls)
    lines += ['  </ul>', f'  <p class="meta" style="margin-top:2rem;">{GENERATED_NOTE}</p>', '</section>',
              '', '</main>', '']
    head_html = head('AgenTrust Agentic Controls | AgenTrust', e(description), f'{BASE}/go/',
                     'index, follow', 'AgenTrust Agentic Controls', f'{BASE}/go/', ld)
    return head_html + body[0] + '\n' + '\n'.join(lines) + '\n' + FOOTER.format(tagline=TAGLINE)


def render_stub(c):
    anchor = f'/go/#{c["slug"]}'
    extra = (f'<meta http-equiv="refresh" content="0; url={anchor}">\n'
             f'<link rel="stylesheet" href="/design-system.css?v={CSS_VERSION}">\n'
             '</head>\n<body class="at-page">\n')
    body = f'''<main>
<section>
  <span class="label">AgenTrust Agentic Controls</span>
  <h2>{e(c["name"])}</h2>
  <p>Redirecting to <a href="{anchor}">the control set</a>.</p>
</section>
</main>

'''
    return (head(f'{e(c["name"])} | AgenTrust Agentic Controls', e(c['requirement']), f'{BASE}{anchor}',
                 'noindex, follow', e(c['name']), f'{BASE}{anchor}', extra)
            + body + FOOTER.format(tagline=TAGLINE))


def outputs(controls):
    pages = {GO / 'index.html': render_index(controls)}
    for c in controls:
        pages[GO / c['slug'] / 'index.html'] = render_stub(c)
    return pages


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='fail if any page differs from the data')
    args = parser.parse_args()

    _, controls = load()
    pages = outputs(controls)
    expected_stubs = {path.parent.name for path in pages if path.parent != GO}
    orphaned = sorted(p.parent.name for p in GO.glob('*/index.html') if p.parent.name not in expected_stubs)
    if orphaned:
        raise SystemExit('Permalinks with no control in the data: ' + ', '.join(orphaned) +
                         '. Published permalinks are cited externally; restore the control or retire the '
                         'page deliberately in its own change.')

    stale = [p for p, text in pages.items() if not p.exists() or p.read_text(encoding='utf-8') != text]
    if args.check:
        if stale:
            names = ', '.join(str(p.relative_to(ROOT)).replace('\\', '/') for p in stale[:5])
            more = f' and {len(stale) - 5} more' if len(stale) > 5 else ''
            raise SystemExit(f'{len(stale)} /go/ page(s) differ from data/agentic-controls.json: {names}{more}. '
                             'Run python tools/build-controls.py and commit the result.')
        print(f'PASS /go/ matches data/agentic-controls.json: index plus {len(controls)} permalinks')
        return
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(pages[path], encoding='utf-8', newline='\n')
    print(f'Wrote {len(stale)} of {len(pages)} /go/ pages from data/agentic-controls.json')


if __name__ == '__main__':
    sys.exit(main())
