"""The one header every agentrust-io.com page carries.

Edit the menu here, then run `python tools/build-header.py` to stamp it into the
hand-written pages. tools/build-controls.py (/go/) and tools/build-discovery.py
(/marketplace/catalog/) import render() directly, so their --check and
build-header's --check agree byte for byte. CI runs all three.

The header styles live in design-system.css under `.hub-header`, and hub-nav.js
adds the mobile Menu toggle.

CSS_VERSION is the cache-bust for the two files every AgenTrust site loads from
agentrust-io.com: design-system.css and supernav.js. They are served with a
four-hour max-age, so bump it when either file changes. build-header.py stamps it
into the hub pages; the seven MkDocs sites pin the same number in mkdocs.yml, and
tools/check-availability.py names any of them that lags.
"""
from html import escape

CSS_VERSION = '21'

START = '<!-- site-header:start (generated by tools/build-header.py from tools/site_header.py) -->'
END = '<!-- site-header:end -->'

# (label, href) for top-level links, and (summary, [(label, href), ...]) for menus.
MENU = [
    ('Verify', '/verify/'),
    ('Specs', [
        ('Model-weight custody (WCM)', 'https://wcm.agentrust-io.com'),
        ('Agent identity (Manifest)', 'https://manifest.agentrust-io.com'),
        ('Tool-call enforcement (cMCP)', 'https://cmcp.agentrust-io.com'),
        ('Agent delegation (cA2A)', 'https://ca2a.agentrust-io.com'),
        ('Runtime evidence (TRACE)', 'https://trace.agentrust-io.com'),
        ('TRACE Registry', '/registry/'),
        ('TRACE conformance suite', 'https://tests.agentrust-io.com'),
    ]),
    ('Build', [
        ('Get started', '/quickstart/'),
        ('Demos', '/demos/'),
        ('Telemetry', '/telemetry/'),
        ('Marketplace', '/marketplace/'),
    ]),
    ('Community', '/community/'),
    ('GitHub', 'https://github.com/agentrust-io'),
]


def _link(label, href, page, indent):
    current = ' aria-current="page"' if href == page else ''
    return f'{indent}<li><a href="{escape(href)}"{current}>{escape(label)}</a></li>'


def render(page=None, section=None, script=True):
    """Return the stamped header block, markers included, with no trailing newline.

    page is the path of the page being rendered; the matching link gets
    aria-current="page". section names the menu the page belongs to when it is not
    itself a menu entry (for example 'Specs' for /go/); a page listed inside a menu
    marks that menu without being told. script=False leaves out hub-nav.js for a
    page that must work without JavaScript; its links then stay visible on phones.
    """
    lines = [
        START,
        '<a class="skip-link" href="#main">Skip to content</a>',
        '<header class="hub-header">',
        '  <div class="header-inner">',
        '    <a href="/" class="logo">AgenTrust</a>',
        '    <nav aria-label="Primary">',
        '      <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-links" hidden>Menu</button>',
        '      <ul class="header-nav" id="primary-links">',
    ]
    for label, target in MENU:
        if isinstance(target, str):
            lines.append(_link(label, target, page, '        '))
            continue
        marked = section == label or any(href == page for _, href in target)
        css = 'spec-menu is-current' if marked else 'spec-menu'
        lines.append(f'        <li class="{css}"><details><summary>{escape(label)}</summary><ul>')
        lines += [_link(child, href, page, '          ') for child, href in target]
        lines.append('        </ul></details></li>')
    lines += [
        '      </ul>',
        '    </nav>',
        '  </div>',
        '</header>',
    ]
    if script:
        lines.append('<script src="/hub-nav.js" defer></script>')
    lines.append(END)
    return '\n'.join(lines)
